import '../src/styles/globals.css';

import { UserProvider } from '@auth0/nextjs-auth0/client';

import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';

import Template from './template';

import theme from '../src/styles/theme';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang='en'>
            <UserProvider>
                <body className='my-first-nextjs-site'>
                    <AppRouterCacheProvider>
                        <ThemeProvider theme={theme}>
                            <CssBaseline />
                            <Template>{children}</Template>
                        </ThemeProvider>
                    </AppRouterCacheProvider>
                </body>
            </UserProvider>
        </html>
    );
}
